### ISSUE TITLE
Android Crash in Fingerprint: "User authentication required"

### ISSUE THREAD

**Issue by petrfuka** [wultra/powerauth-mobile-sdk#199]
Production crash, PowerAuth crashes when initializing fingerprint. Possibly because the devices was not secured with PIN, pattern or password (not tested).

Crash on old PowerAuth 0.16.5 but issue probably still exists.

Reported stack trace:
```
Fatal Exception: java.security.ProviderException: Keystore operation failed
       at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:365)
       at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintKeystore.generateDefaultKey(SourceFile:100)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationHandler.initCrypto(SourceFile:208)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationDialogFragment.onCreate(SourceFile:142)
       at android.app.Fragment.performCreate(Fragment.java:2593)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2421)
       at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
       at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by android.security.KeyStoreException: User authentication required
       at android.security.KeyStore.getKeyStoreException(KeyStore.java:1112)
       at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:366)
       at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintKeystore.generateDefaultKey(SourceFile:100)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationHandler.initCrypto(SourceFile:208)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationDialogFragment.onCreate(SourceFile:142)
       at android.app.Fragment.performCreate(Fragment.java:2593)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2421)
       at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
       at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by hvge** [comment]
Do you have more information about the device? This might be a device specific issue.
