### ISSUE TITLE
Android Crash in Encryptor from network problems

### ISSUE THREAD

**Issue by petrfuka** [wultra/powerauth-mobile-sdk#201]
Production crash, network/server problems resulted in application crash.

Crash on old PowerAuth 0.16.5 but issue probably still exists.

Stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at io.getlime.security.powerauth.e2ee.PA2RequestResponseNonPersonalizedEncryptor.decryptResponse(SourceFile:118)
       at io.getlime.security.powerauth.e2ee.PA2RequestResponseNonPersonalizedEncryptor.decryptResponse(SourceFile:161)
       at cz.equabank.mobilebanking.activity.ActivationPasswordActivity$1.doStuffOnResponse(SourceFile:211)
       at cz.equabank.mobilebanking.rest.RestCallBack.handleResponse(SourceFile:72)
       at cz.equabank.mobilebanking.rest.BaseCallBack.onResponse(SourceFile:28)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(SourceFile:70)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6635)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by petrfuka** [comment]
I just noticed that we are passing the null object to PA Encryptor ourselves, we should handle that in our code.

**Comment by petrdvorak** [comment]
@petrfuka Thank you for closing this one. There are two comments from my end:

- It was our issue - we should have handled invalid input.
- We will be removing current encryptors in favour of generic ECIES encryptors.
