### ISSUE TITLE
Android Crash on Fingerprint dialog resume

### ISSUE THREAD

**Issue by petrfuka** [wultra/powerauth-mobile-sdk#202]
Production crash on old PowerAuth 0.16.5.

Stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {...LoginActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:2019)
       at android.os.Parcel.readException(Parcel.java:1959)
       at android.hardware.fingerprint.IFingerprintService$Stub$Proxy.authenticate(IFingerprintService.java:302)
       at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:546)
       at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:506)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationHandler.startListening(FingerprintAuthenticationHandler.java:131)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationDialogFragment.onResume(FingerprintAuthenticationDialogFragment.java:250)
       at android.app.Fragment.performResume(Fragment.java:2554)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1322)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
       at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2196)
       at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2989)
       at android.app.FragmentController.dispatchResume(FragmentController.java:200)
       at android.app.Activity.performResume(Activity.java:7165)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by hvge** [comment]
Do you have more information about the device? This might be a device specific issue.

**Comment by petrfuka** [comment]
Issue detected again on PA version 0.20.0 with slightly different stack trace.
Device is Xiaomi Redmi 3S, Android 9

In the older PA version, it's on many different phone models and manufacturers:
~50% Huawei, 15% each of LG, Nokia and ASUS, a few Xiaomi. Android versions 6-9.

Stack trace: (the tacked-on RemoteException looks weird but probably belongs there, it was actually in the previous occurence as well)
`
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {cz.equabank.mobilebanking/cz.equabank.mobilebanking.activity.LoginActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3823)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3855)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6724)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at android.os.Parcel.createException(Parcel.java:1956)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.os.Parcel.readException(Parcel.java:1868)
       at android.hardware.fingerprint.IFingerprintService$Stub$Proxy.authenticate(IFingerprintService.java:323)
       at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:431)
       at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:389)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationHandler.startListening(FingerprintAuthenticationHandler.java:22)
       at io.getlime.security.powerauth.keychain.fingerprint.FingerprintAuthenticationDialogFragment.onResume(FingerprintAuthenticationDialogFragment.java:18)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:18)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:834)
       at androidx.fragment.app.FragmentManagerImpl.n(FragmentManagerImpl.java:38)
       at androidx.fragment.app.FragmentManagerImpl.g(FragmentManagerImpl.java:47)
       at androidx.fragment.app.BackStackRecord.jb(BackStackRecord.java:170)
       at androidx.fragment.app.FragmentManagerImpl.b(FragmentManagerImpl.java:38)
       at androidx.fragment.app.FragmentManagerImpl.a(FragmentManagerImpl.java:114)
       at androidx.fragment.app.FragmentManagerImpl.c(FragmentManagerImpl.java:88)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:21)
       at androidx.fragment.app.FragmentManagerImpl.cn(FragmentManagerImpl.java:9)
       at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:6)
       at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.jd(FragmentActivity.java:2)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:3)
       at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
       at cz.equabank.mobilebanking.activity.BaseActivity.onPostResume(BaseActivity.java:450)
       at android.app.Activity.performResume(Activity.java:7325)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3815)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3855)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6724)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.fingerprint.FingerprintService.isForegroundActivity(FingerprintService.java:777)
	at com.android.server.fingerprint.FingerprintService.canUseFingerprint(FingerprintService.java:815)
	at com.android.server.fingerprint.FingerprintService.access$1900(FingerprintService.java:102)
	at com.android.server.fingerprint.FingerprintService$FingerprintServiceWrapper.authenticate(FingerprintService.java:1188)
	at android.hardware.fingerprint.IFingerprintService$Stub.onTransact(IFingerprintService.java:74)
`

**Comment by romanstrobl** [comment]
This issue will have to wait for the next release.

**Comment by hvge** [comment]
I believe, the crash is really in the `com.android.server.fingerprint.FingerprintService`, where private method `isForegroundActivity()` is accessing a list of app processes. Looks like the list can be `null` in some circumstances and that's not properly handled in the function. Look for the problematic code -  [FingerprintService.java](https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/fingerprint/FingerprintService.java#771), with a slightly different line (771 vs 777).

Our upcoming SDK `1.2.0` contains a complete rework of biometric support, so I think, this is no longer a thing. I believe that this is somehow related to a stopping and resuming the application, while the fingerprint authentication is active. This is no longer a thing in `1.2.0`, because:

- We properly handle cancel events from the system (reported to fingerprint manager's listener when app is going to background)
- We don't allow to reuse the `FingerprintManager`. Once it has result, failure, or was canceled, we no longer allow reuse the acquired instance.

Otherwise I honestly don't know how we can fix or workaround this android sh**t. I found that also other libraries suffer with a similar problem. For example [RxFingerprint](https://github.com/Mauin/RxFingerprint/issues/42).

**Comment by hvge** [comment]
I was thinking about the problem for once more time and I think we should catch that NPE and report cancel in that situation. I'll prepare fix for `develop`, `1.1.x`, `0.20.x` branches.

**Comment by ThatsNeha** [comment]
Got this crash from firebase:

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:2019)
       at android.os.Parcel.readException(Parcel.java:1959)
       at android.hardware.fingerprint.IFingerprintService$Stub$Proxy.authenticate(IFingerprintService.java:302)
       at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:532)
       at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:492)
       at androidx.core.hardware.fingerprint.FingerprintManagerCompat.authenticate(FingerprintManagerCompat.java:113)
       at androidx.biometric.FingerprintHelperFragment.onCreateView(FingerprintHelperFragment.java:261)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
       at android.app.Activity.performStart(Activity.java:7043)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2782)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2897)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6548)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by hvge** [comment]
@ThatsNeha well, in that case, you should report this to firebase. I don't see how this is related to our library :)
