### ISSUE TITLE
Android: Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-mobile-sdk#220]
One of our clients did report to us following rare, dynamic library linking error:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libPowerAuth2Module.so" (built with --hash-style=gnu?)
       at java.lang.Runtime.loadLibrary(Runtime.java:364)
       at java.lang.System.loadLibrary(System.java:526)
       at io.getlime.security.powerauth.core.Session.(SourceFile:29)
       at io.getlime.security.powerauth.sdk.PowerAuthSDK$Builder.build(PowerAuthSDK.java:167)
```
Device: Lenovo A6000, Android 4.4.4

According to this [SO discussion](https://stackoverflow.com/questions/28638809/android-ndk-unsatisfiedlinkerror-dlopen-failed-empty-missing-dt-hash), it looks like that we need to fix the linking step in our NDK build.

I'll fix this for `develop` branch for upcoming `1.1.0` release and then I'll back-port that fix to `release/0.20.x` branch.

**Comment by hvge** [comment]
Looks like that `--hash-style=both` linker parameter does the job. Here's list of ELF sections **before** the change:
```bash
hvge@trogdor:bin$ ./x86_64-linux-android-readelf -d ~/Dev/lime/tmp/verz/1.0.0/before/libPowerAuth2Module.so 

Dynamic section at offset 0x199128 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x000000000000000e (SONAME)             Library soname: [libPowerAuth2Module.so]
 0x0000000000000019 (INIT_ARRAY)         0x190398
 0x000000000000001b (INIT_ARRAYSZ)       24 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x1903b0
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x0000000000000004 (HASH)               0x228
 0x0000000000000005 (STRTAB)             0x1bd0
 0x0000000000000006 (SYMTAB)             0x880
 0x000000000000000a (STRSZ)              6303 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x1a9328
 0x0000000000000002 (PLTRELSZ)           2904 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x2d3c8
 0x0000000000000007 (RELA)               0x3650
 0x0000000000000008 (RELASZ)             171384 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x3610
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0x3470
 0x000000006ffffff9 (RELACOUNT)          7131
 0x0000000000000000 (NULL)               0x0
```
 ...and **after** the change:
```bash
hvge@trogdor:bin$ ./x86_64-linux-android-readelf -d ~/Dev/lime/tmp/verz/1.0.0/after/libPowerAuth2Module.so 

Dynamic section at offset 0x19a118 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x000000000000000e (SONAME)             Library soname: [libPowerAuth2Module.so]
 0x0000000000000019 (INIT_ARRAY)         0x191388
 0x000000000000001b (INIT_ARRAYSZ)       24 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x1913a0
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x0000000000000004 (HASH)               0x228
 0x000000006ffffef5 (GNU_HASH)           0x880
 0x0000000000000005 (STRTAB)             0x1e68
 0x0000000000000006 (SYMTAB)             0xb18
 0x000000000000000a (STRSZ)              6303 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x1aa328
 0x0000000000000002 (PLTRELSZ)           2904 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x2d660
 0x0000000000000007 (RELA)               0x38e8
 0x0000000000000008 (RELASZ)             171384 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x38a8
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0x3708
 0x000000006ffffff9 (RELACOUNT)          7131
 0x0000000000000000 (NULL)               0x0
``` 

The new `GNU_HASH` section has been added.
