### ISSUE TITLE
Android SDK not working with android.enableR8.fullMode=true

### ISSUE THREAD

**Issue by jaroslavhavelik** [wultra/powerauth-mobile-sdk#526]
After enabling full mode within R8 via `android.enableR8.fullMode=true` (or by default since AGP 8+) we are getting the following error when attempting to enroll activation:

`io.getlime.security.powerauth.networking.exceptions.FailedApiException: Unable to invoke no-args constructor for class io.getlime.security.powerauth.networking.model.response.EciesEncryptedResponse. Registering an InstanceCreator with Gson for this type may fix this problem.
                                                                                                    	at io.getlime.security.powerauth.networking.client.HttpRequestHelper.buildResponseException(HttpRequestHelper.java:363)
                                                                                                    	at io.getlime.security.powerauth.networking.client.HttpRequestHelper.buildResponse(HttpRequestHelper.java:243)
                                                                                                    	at io.getlime.security.powerauth.networking.client.HttpClientTask.doInBackground(HttpClientTask.java:201)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)`

Can you please suggest (or even better update consumer proguard rules) so we can use full mode of R8.

**Comment by hvge** [comment]
> Backport to `release/1.7.x`

**Comment by kober32** [comment]
This should be fixed by adding following rule to the https://github.com/wultra/powerauth-mobile-sdk/blob/develop/proj-android/PowerAuthLibrary/proguard-rules.pro
```
-keep class io.getlime.security.powerauth.networking.model.** {
    <fields>;
}
```
